[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lightningrod-ai"
version = "0.2.2"
description = "Predict anything with AI. Python SDK for Foresight forecasting models, built on top of OpenAI compatible inference API."
readme = "README.md"
requires-python = ">=3.10"
keywords = [
    "forecasting",
    "probabilistic prediction",
    "OpenAI-compatible API",
    "foresight",
    "LLM inference",
]
license = { file = "LICENSE" }
authors = [
    {name = "Lightning Rod Labs", email = "support@lightningrod.ai"}
]
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.0.0",
    "httpx>=0.25.0",
    "attrs>=23.1.0",
    "python-dateutil>=2.8.0",
    "pyarrow>=14.0.0",
    "fsspec>=2023.0.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "build>=1.0.0",
    "openapi-python-client>=0.15.0",
    "pytest>=7.0.0",
    "twine>=5.0.0",
]
transfer = [
    "google-cloud-storage>=2.0.0",
]
visual = [
    "PyMuPDF>=1.24.0",
    "openai>=1.0.0",
]
extract = [
    "openai>=1.0.0",
    "pypdf>=4.0.0",
    "pypdfium2>=4.0.0",
    "pillow>=10.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[project.urls]
Homepage = "https://lightningrod.ai/sdk"
Repository = "https://github.com/lightning-rod-labs/lightningrod-python-sdk"

