from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.sample_dataset_config import SampleDatasetConfig


T = TypeVar("T", bound="TrainingConfig")


@_attrs_define
class TrainingConfig:
    r"""
    Attributes:
        dataset (SampleDatasetConfig): Configuration for loading a dataset of samples from the sample database.

            Fields:
                id: Dataset ID used to fetch samples from the DB.
                sample_ids: The specific sample IDs to load from that dataset.
                prompt_template: Optional custom prompt format. If None, uses the default section-based layout
                    (QUESTION / CONTEXT / ANSWER FORMAT / CLOSE DATE).
                multiple_choice_options: Advanced override for multi-choice datasets where the option map can't be
                    derived from the samples themselves. By default, options are auto-extracted from the
                    question text (which works for any question generated by our standard pipeline, since
                    options are embedded as `option_0: ...` lines). Only set this if samples were imported
                    from an external source (e.g. Metaculus) where the question text is plain prose and
                    options were stored separately.

                    Example (standard pipeline — leave as None):
                        "What will the Fed decide by March 2025?\noption_0: Rate increase\noption_1: No change"
                        → options auto-extracted, no override needed.

                    Example (external import — override required):
                        question text: "What will the Fed decide by March 2025?" (no option lines)
                        multiple_choice_options='{"option_0": "Rate increase", "option_1": "No change", "option_2": "Rate
            cut"}'
        base_model_id (str): Base model ID (e.g. Qwen/Qwen3-8B, Qwen/Qwen3-32B, openai/gpt-oss-20b, openai/gpt-oss-120b)
        training_steps (int): Number of training loop iterations
        batch_size (int | None | Unset): Rows per batch; used to slice train_rows each step
        lora_rank (int | None | Unset): LoRA adapter rank passed to create_lora_training_client_async
        learning_rate (float | None | Unset): Step size for weight updates; higher values learn faster but may overshoot
        adam_beta1 (float | None | Unset): Exponential decay rate for first-moment estimates (moving average of
            gradients)
        adam_beta2 (float | None | Unset): Exponential decay rate for second-moment estimates (moving average of squared
            gradients)
        num_rollouts (int | None | Unset): Samples per prompt for GRPO
        max_response_length (int | None | Unset): Max tokens for sampling
        start_idx (int | None | Unset): Row index to skip at start; train_rows = train_rows[start_idx:]
        save_frequency (int | Unset): The frequency at which to save checkpoints, in training steps. Default: 10.
    """

    dataset: SampleDatasetConfig
    base_model_id: str
    training_steps: int
    batch_size: int | None | Unset = UNSET
    lora_rank: int | None | Unset = UNSET
    learning_rate: float | None | Unset = UNSET
    adam_beta1: float | None | Unset = UNSET
    adam_beta2: float | None | Unset = UNSET
    num_rollouts: int | None | Unset = UNSET
    max_response_length: int | None | Unset = UNSET
    start_idx: int | None | Unset = UNSET
    save_frequency: int | Unset = 10
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        dataset = self.dataset.to_dict()

        base_model_id = self.base_model_id

        training_steps = self.training_steps

        batch_size: int | None | Unset
        if isinstance(self.batch_size, Unset):
            batch_size = UNSET
        else:
            batch_size = self.batch_size

        lora_rank: int | None | Unset
        if isinstance(self.lora_rank, Unset):
            lora_rank = UNSET
        else:
            lora_rank = self.lora_rank

        learning_rate: float | None | Unset
        if isinstance(self.learning_rate, Unset):
            learning_rate = UNSET
        else:
            learning_rate = self.learning_rate

        adam_beta1: float | None | Unset
        if isinstance(self.adam_beta1, Unset):
            adam_beta1 = UNSET
        else:
            adam_beta1 = self.adam_beta1

        adam_beta2: float | None | Unset
        if isinstance(self.adam_beta2, Unset):
            adam_beta2 = UNSET
        else:
            adam_beta2 = self.adam_beta2

        num_rollouts: int | None | Unset
        if isinstance(self.num_rollouts, Unset):
            num_rollouts = UNSET
        else:
            num_rollouts = self.num_rollouts

        max_response_length: int | None | Unset
        if isinstance(self.max_response_length, Unset):
            max_response_length = UNSET
        else:
            max_response_length = self.max_response_length

        start_idx: int | None | Unset
        if isinstance(self.start_idx, Unset):
            start_idx = UNSET
        else:
            start_idx = self.start_idx

        save_frequency = self.save_frequency

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "dataset": dataset,
                "base_model_id": base_model_id,
                "training_steps": training_steps,
            }
        )
        if batch_size is not UNSET:
            field_dict["batch_size"] = batch_size
        if lora_rank is not UNSET:
            field_dict["lora_rank"] = lora_rank
        if learning_rate is not UNSET:
            field_dict["learning_rate"] = learning_rate
        if adam_beta1 is not UNSET:
            field_dict["adam_beta1"] = adam_beta1
        if adam_beta2 is not UNSET:
            field_dict["adam_beta2"] = adam_beta2
        if num_rollouts is not UNSET:
            field_dict["num_rollouts"] = num_rollouts
        if max_response_length is not UNSET:
            field_dict["max_response_length"] = max_response_length
        if start_idx is not UNSET:
            field_dict["start_idx"] = start_idx
        if save_frequency is not UNSET:
            field_dict["save_frequency"] = save_frequency

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.sample_dataset_config import SampleDatasetConfig

        d = dict(src_dict)
        dataset = SampleDatasetConfig.from_dict(d.pop("dataset"))

        base_model_id = d.pop("base_model_id")

        training_steps = d.pop("training_steps")

        def _parse_batch_size(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        batch_size = _parse_batch_size(d.pop("batch_size", UNSET))

        def _parse_lora_rank(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        lora_rank = _parse_lora_rank(d.pop("lora_rank", UNSET))

        def _parse_learning_rate(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        learning_rate = _parse_learning_rate(d.pop("learning_rate", UNSET))

        def _parse_adam_beta1(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        adam_beta1 = _parse_adam_beta1(d.pop("adam_beta1", UNSET))

        def _parse_adam_beta2(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        adam_beta2 = _parse_adam_beta2(d.pop("adam_beta2", UNSET))

        def _parse_num_rollouts(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        num_rollouts = _parse_num_rollouts(d.pop("num_rollouts", UNSET))

        def _parse_max_response_length(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        max_response_length = _parse_max_response_length(d.pop("max_response_length", UNSET))

        def _parse_start_idx(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        start_idx = _parse_start_idx(d.pop("start_idx", UNSET))

        save_frequency = d.pop("save_frequency", UNSET)

        training_config = cls(
            dataset=dataset,
            base_model_id=base_model_id,
            training_steps=training_steps,
            batch_size=batch_size,
            lora_rank=lora_rank,
            learning_rate=learning_rate,
            adam_beta1=adam_beta1,
            adam_beta2=adam_beta2,
            num_rollouts=num_rollouts,
            max_response_length=max_response_length,
            start_idx=start_idx,
            save_frequency=save_frequency,
        )

        training_config.additional_properties = d
        return training_config

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
