from enum import Enum


class TransformType(str, Enum):
    BIGQUERY_SEED_GENERATOR = "BIGQUERY_SEED_GENERATOR"
    CSV_SEED_GENERATOR = "CSV_SEED_GENERATOR"
    FILESET_CONTEXT_GENERATOR = "FILESET_CONTEXT_GENERATOR"
    FILESET_DOCUMENT_CONTEXT_GENERATOR = "FILESET_DOCUMENT_CONTEXT_GENERATOR"
    FILESET_DOCUMENT_LABELER = "FILESET_DOCUMENT_LABELER"
    FILESET_QUERY_SEED_GENERATOR = "FILESET_QUERY_SEED_GENERATOR"
    FILESET_RAG_LABELER = "FILESET_RAG_LABELER"
    FILESET_SEED_GENERATOR = "FILESET_SEED_GENERATOR"
    FILTER_CRITERIA = "FILTER_CRITERIA"
    FORWARD_LOOKING_QUESTION_GENERATOR = "FORWARD_LOOKING_QUESTION_GENERATOR"
    GDELT_SEED_GENERATOR = "GDELT_SEED_GENERATOR"
    KEY_DEDUPLICATION = "KEY_DEDUPLICATION"
    MOCK = "MOCK"
    NEWS_CONTEXT_GENERATOR = "NEWS_CONTEXT_GENERATOR"
    NEWS_SEED_GENERATOR = "NEWS_SEED_GENERATOR"
    PIPELINE = "PIPELINE"
    QUESTION_AND_LABEL_GENERATOR = "QUESTION_AND_LABEL_GENERATOR"
    QUESTION_FILTER = "QUESTION_FILTER"
    QUESTION_GENERATOR = "QUESTION_GENERATOR"
    QUESTION_PIPELINE = "QUESTION_PIPELINE"
    QUESTION_QUALITY_SCORER = "QUESTION_QUALITY_SCORER"
    QUESTION_RENDERER = "QUESTION_RENDERER"
    ROLLOUT_GENERATOR = "ROLLOUT_GENERATOR"
    ROLLOUT_SCORER = "ROLLOUT_SCORER"
    SCORE_FILTER = "SCORE_FILTER"
    TEMPLATE_QUESTION_GENERATOR = "TEMPLATE_QUESTION_GENERATOR"
    TOPIC_TREE_SEED_GENERATOR = "TOPIC_TREE_SEED_GENERATOR"
    WEB_SEARCH_LABELER = "WEB_SEARCH_LABELER"

    def __str__(self) -> str:
        return str(self.value)
