from enum import Enum


class TransformType(str, Enum):
    FILTER_CRITERIA = "FILTER_CRITERIA"
    FORWARD_LOOKING_QUESTION_GENERATOR = "FORWARD_LOOKING_QUESTION_GENERATOR"
    GDELT_SEED_GENERATOR = "GDELT_SEED_GENERATOR"
    NEWS_SEED_GENERATOR = "NEWS_SEED_GENERATOR"
    PIPELINE = "PIPELINE"
    QUESTION_GENERATOR = "QUESTION_GENERATOR"
    QUESTION_PIPELINE = "QUESTION_PIPELINE"
    QUESTION_QUALITY_SCORER = "QUESTION_QUALITY_SCORER"
    SCORE_FILTER = "SCORE_FILTER"
    SCULPT = "SCULPT"
    WEB_SEARCH_LABELER = "WEB_SEARCH_LABELER"

    def __str__(self) -> str:
        return str(self.value)
