"""
Lightning Rod Python SDK

AI-powered forecasting dataset generation platform.
"""

from lightningrod.client import LightningRod
from lightningrod.prediction import (
    AnswerType,
    ReasoningEffort,
    BinaryPrediction,
    ContinuousPrediction,
    MultiChoicePrediction,
    FreeResponsePrediction,
    Source,
    Usage,
    PredictionResult,
)
from lightningrod._errors import CostEstimateUnavailable
from lightningrod.utils.config import LightningrodAuthError
from lightningrod.filesets.client import UploadResult
from lightningrod.datasets.dataset import SampleDataset, AsyncDataset
from lightningrod.datasets.linting import get_lint_affected_sample_ids
from lightningrod import preprocessing, training, utils, display
from lightningrod.utils.sample import create_sample
from lightningrod.utils.models import open_router_model
from lightningrod.utils.examples import binary_example, continuous_example, multiple_choice_example
from lightningrod.training import prepare_for_training, FilterParams, DedupParams, SplitParams
from lightningrod.training.client import GRPOTrainingConfig, SFTTrainingConfig, TrainingMethodConfig
from lightningrod._display import (
    display_lint_overview,
    display_lint_detailed,
)
from lightningrod._generated.models import (
    TransformJob,
    TransformJobStatus,
    BigQuerySeedGenerator,
    NewsSeedGenerator,
    GdeltSeedGenerator,
    NewsContextGenerator,
    QuestionGenerator,
    QuestionAndLabelGenerator,
    ForwardLookingQuestionGenerator,
    QuestionPipeline,
    QuestionRenderer,
    TemplateQuestionGenerator,
    RolloutGenerator,
    ModelConfig,
    ModelSourceType,
    Label,
    Rollout,
    RolloutScorer,
    WebSearchLabeler,
    FilterCriteria,
    Sample,
    SampleMeta,
    Seed,
    BinaryAnswerType,
    ContinuousAnswerType,
    MultipleChoiceAnswerType,
    FreeResponseAnswerType,
    FileSetSeedGenerator,
    FileSetDocumentContextGenerator,
    FileSetDocumentLabeler,
    QdrantContextGenerator,
    QdrantRAGLabeler,
    DocumentContext,
    TemporalConstraint,
    CreateFileSetRequest,
    CreateFileUploadResponse,
    FileSetMetadataSchemaInput,
    MetadataFieldDefinitionInput,
    MetadataFieldType,
    TopicTreeSeedGenerator,
    CsvSeedGenerator,
    EvalModel,
    EvalResultsDownloadResponse,
    ReasoningComparisonOptions,
    WebSearchContextGenerator,
    EmbeddingDeduplication,
    EmbeddingDeduplicationSynonyms,
)

__version__ = "0.2.0"
__all__ = [
    "preprocessing",
    "training",
    "utils",
    "display",
    "AsyncDataset",
    "BigQuerySeedGenerator",
    "binary_example",
    "BinaryAnswerType",
    "CostEstimateUnavailable",
    "LightningrodAuthError",
    "continuous_example",
    "ContinuousAnswerType",
    "multiple_choice_example",
    "MultipleChoiceAnswerType",
    "FreeResponseAnswerType",
    "SampleDataset",
    "DocumentContext",
    "display_lint_overview",
    "display_lint_detailed",
    "get_lint_affected_sample_ids",
    "FileSetDocumentContextGenerator",
    "FileSetDocumentLabeler",
    "FileSetSeedGenerator",
    "QdrantContextGenerator",
    "QdrantRAGLabeler",
    "TemporalConstraint",
    "CreateFileSetRequest",
    "CreateFileUploadResponse",
    "FilterCriteria",
    "ForwardLookingQuestionGenerator",
    "GdeltSeedGenerator",
    "Label",
    "LightningRod",
    "AnswerType",
    "ReasoningEffort",
    "BinaryPrediction",
    "ContinuousPrediction",
    "MultiChoicePrediction",
    "FreeResponsePrediction",
    "Source",
    "Usage",
    "PredictionResult",
    "ModelConfig",
    "ModelSourceType",
    "NewsContextGenerator",
    "NewsSeedGenerator",
    "QuestionAndLabelGenerator",
    "QuestionGenerator",
    "QuestionPipeline",
    "QuestionRenderer",
    "create_sample",
    "FileSetMetadataSchemaInput",
    "MetadataFieldDefinitionInput",
    "MetadataFieldType",
    "open_router_model",
    "Rollout",
    "RolloutScorer",
    "RolloutGenerator",
    "prepare_for_training",
    "FilterParams",
    "DedupParams",
    "SplitParams",
    "GRPOTrainingConfig",
    "SFTTrainingConfig",
    "TrainingMethodConfig",
    "Sample",
    "SampleMeta",
    "Seed",
    "TemplateQuestionGenerator",
    "TransformJob",
    "TransformJobStatus",
    "WebSearchLabeler",
    "TopicTreeSeedGenerator",
    "CsvSeedGenerator",
    "EvalModel",
    "EvalResultsDownloadResponse",
    "ReasoningComparisonOptions",
    "WebSearchContextGenerator",
    "EmbeddingDeduplication",
    "EmbeddingDeduplicationSynonyms",
]
